<a href="https://colab.research.google.com/github/gisellegonzalezm/Operations-Logistics-Samples/blob/main/calculator_py_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
# Import pandas
import pandas as pd

# Read the CSV file
df = pd.read_csv("sample_imports.csv")

# Show the first rows
print(df.head())

  Shipment_ID            Supplier      Country            Product  HS_Code  \
0      IMP001  Shanghai Steel Co.        China        Steel Pipes     7306
1      IMP002  Hamburg Industrial      Germany  Industrial Valves     8481
2      IMP003    Texas Pumps Inc.          USA    Hydraulic Pumps     8413
3      IMP004     Osaka Tech Ltd.        Japan            Sensors     9026
4      IMP005    Seoul Components  South Korea  Electronic Boards     8534

  Incoterm  Product_Value_USD  Inland_Transport_USD  Freight_USD  \
0      FOB              18500                     0         2100
1      CIF              24000                     0            0
2      EXW              15000                   500         3000
3      FOB              12000                     0         1800
4      CIF              19500                     0            0

   Insurance_USD  Duty_Rate  VAT_Rate Destination_Port
0            180         10        19        Cartagena
1              0          5        19        Cartagena
2            250          0        19     Buenaventura
3            150          5        19        Cartagena
4              0         10        19        Cartagena

In [6]:
df.head()

,Shipment_ID,Supplier,Country,Product,HS_Code,Incoterm,Product_Value_USD,Inland_Transport_USD,Freight_USD,Insurance_USD,Duty_Rate,VAT_Rate,Destination_Port
0,IMP001,Shanghai Steel Co.,China,Steel Pipes,7306,FOB,18500,0,2100,180,10,19,Cartagena
1,IMP002,Hamburg Industrial,Germany,Industrial Valves,8481,CIF,24000,0,0,0,5,19,Cartagena
2,IMP003,Texas Pumps Inc.,USA,Hydraulic Pumps,8413,EXW,15000,500,3000,250,0,19,Buenaventura
3,IMP004,Osaka Tech Ltd.,Japan,Sensors,9026,FOB,12000,0,1800,150,5,19,Cartagena
4,IMP005,Seoul Components,South Korea,Electronic Boards,8534,CIF,19500,0,0,0,10,19,Cartagena

In [7]:
df.shape

(15, 13)

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 13 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Shipment_ID           15 non-null     object
 1   Supplier              15 non-null     object
 2   Country               15 non-null     object
 3   Product               15 non-null     object
 4   HS_Code               15 non-null     int64
 5   Incoterm              15 non-null     object
 6   Product_Value_USD     15 non-null     int64
 7   Inland_Transport_USD  15 non-null     int64
 8   Freight_USD           15 non-null     int64
 9   Insurance_USD         15 non-null     int64
 10  Duty_Rate             15 non-null     int64
 11  VAT_Rate              15 non-null     int64
 12  Destination_Port      15 non-null     object
dtypes: int64(7), object(6)
memory usage: 1.7+ KB

In [9]:
df.describe()

,HS_Code,Product_Value_USD,Inland_Transport_USD,Freight_USD,Insurance_USD,Duty_Rate,VAT_Rate
count,15.000000,15.000000,15.000000,15.000000,15.000000,15.000000,15.0
mean,7297.400000,16926.666667,126.666667,1376.666667,126.666667,6.333333,19.0
std,1888.459569,7032.523086,222.699883,1176.688250,101.465453,3.994043,0.0
min,3901.000000,8700.000000,0.000000,0.000000,0.000000,0.000000,19.0
25%,6604.500000,11500.000000,0.000000,0.000000,0.000000,5.000000,19.0
50%,8414.000000,15000.000000,0.000000,1600.000000,160.000000,5.000000,19.0
75%,8493.000000,20500.000000,175.000000,2150.000000,185.000000,10.000000,19.0
max,9026.000000,32500.000000,600.000000,3500.000000,300.000000,15.000000,19.0

In [12]:
df.isnull().sum()

Shipment_ID             0
Supplier                0
Country                 0
Product                 0
HS_Code                 0
Incoterm                0
Product_Value_USD       0
Inland_Transport_USD    0
Freight_USD             0
Insurance_USD           0
Duty_Rate               0
VAT_Rate                0
Destination_Port        0
dtype: int64

In [14]:
def calculate_cif(row):

    if row["Incoterm"] == "CIF":return row["Product_Value_USD"]

    elif row["Incoterm"] == "FOB":
        return (row["Product_Value_USD"]
            + row["Freight_USD"]
            + row["Insurance_USD"])

    elif row["Incoterm"] == "EXW":
        return (row["Product_Value_USD"]
            + row["Inland_Transport_USD"]
            + row["Freight_USD"]
            + row["Insurance_USD"])

In [15]:
df["CIF_Value_USD"] = df.apply(calculate_cif, axis=1)

In [16]:
df[ ["Shipment_ID", "Incoterm", "Product_Value_USD","CIF_Value_USD"]]

   Shipment_ID Incoterm  Product_Value_USD  CIF_Value_USD
0       IMP001      FOB              18500          20780
1       IMP002      CIF              24000          24000
2       IMP003      EXW              15000          18750
3       IMP004      FOB              12000          13950
4       IMP005      CIF              19500          19500
5       IMP006      EXW               9800          12730
6       IMP007      FOB              14500          15570
7       IMP008      CIF              11000          11000
8       IMP009      FOB              13200          14760
9       IMP010      EXW              27500          29900
10      IMP011      FOB              16800          19170
11      IMP012      CIF               9400           9400
12      IMP013      EXW              21500          23840
13      IMP014      FOB              32500          36300
14      IMP015      CIF               8700           8700

In [17]:
df.shape

(15, 14)

Calcular el arancel

In [18]:
df["Duty_USD"] = df["CIF_Value_USD"] * (df["Duty_Rate"] / 100)

In [19]:
df[["Shipment_ID","CIF_Value_USD","Duty_Rate","Duty_USD"]]

   Shipment_ID  CIF_Value_USD  Duty_Rate  Duty_USD
0       IMP001          20780         10    2078.0
1       IMP002          24000          5    1200.0
2       IMP003          18750          0       0.0
3       IMP004          13950          5     697.5
4       IMP005          19500         10    1950.0
5       IMP006          12730          5     636.5
6       IMP007          15570         10    1557.0
7       IMP008          11000         15    1650.0
8       IMP009          14760          5     738.0
9       IMP010          29900          5    1495.0
10      IMP011          19170         10    1917.0
11      IMP012           9400          5     470.0
12      IMP013          23840          5    1192.0
13      IMP014          36300          0       0.0
14      IMP015           8700          5     435.0

Calcular el IVA

In [20]:
df["VAT_USD"] = (df["CIF_Value_USD"] + df["Duty_USD"]) * (df["VAT_Rate"] / 100)

In [21]:
df[["Shipment_ID","VAT_USD"]]

   Shipment_ID   VAT_USD
0       IMP001  4343.020
1       IMP002  4788.000
2       IMP003  3562.500
3       IMP004  2783.025
4       IMP005  4075.500
5       IMP006  2539.635
6       IMP007  3254.130
7       IMP008  2403.500
8       IMP009  2944.620
9       IMP010  5965.050
10      IMP011  4006.530
11      IMP012  1875.300
12      IMP013  4756.080
13      IMP014  6897.000
14      IMP015  1735.650

Calcular el costo total

In [22]:
df["Total_Import_Cost_USD"] = (df["CIF_Value_USD"]+ df["Duty_USD"]+ df["VAT_USD"])

In [23]:
df[[ "Shipment_ID","Incoterm","CIF_Value_USD","Duty_USD","VAT_USD","Total_Import_Cost_USD"]]

,Shipment_ID,Incoterm,CIF_Value_USD,Duty_USD,VAT_USD,Total_Import_Cost_USD
0,IMP001,FOB,20780,2078.0,4343.020,27201.020
1,IMP002,CIF,24000,1200.0,4788.000,29988.000
2,IMP003,EXW,18750,0.0,3562.500,22312.500
3,IMP004,FOB,13950,697.5,2783.025,17430.525
4,IMP005,CIF,19500,1950.0,4075.500,25525.500
5,IMP006,EXW,12730,636.5,2539.635,15906.135
6,IMP007,FOB,15570,1557.0,3254.130,20381.130
7,IMP008,CIF,11000,1650.0,2403.500,15053.500
8,IMP009,FOB,14760,738.0,2944.620,18442.620
9,IMP010,EXW,29900,1495.0,5965.050,37360.050
10,IMP011,FOB,19170,1917.0,4006.530,25093.530
11,IMP012,CIF,9400,470.0,1875.300,11745.300
12,IMP013,EXW,23840,1192.0,4756.080,29788.080
13,IMP014,FOB,36300,0.0,6897.000,43197.000
14,IMP015,CIF,8700,435.0,1735.650,10870.650

In [24]:
df.groupby("Incoterm")["Total_Import_Cost_USD"].mean()

Incoterm
CIF    18636.590000
EXW    26341.691250
FOB    25290.970833
Name: Total_Import_Cost_USD, dtype: float64

In [25]:
df.sort_values(by="Total_Import_Cost_USD", ascending=False)

,Shipment_ID,Supplier,Country,Product,HS_Code,Incoterm,Product_Value_USD,Inland_Transport_USD,Freight_USD,Insurance_USD,Duty_Rate,VAT_Rate,Destination_Port,CIF_Value_USD,Duty_USD,VAT_USD,Total_Import_Cost_USD
13,IMP014,Sydney Mining Equip.,Australia,Mining Parts,8431,FOB,32500,0,3500,300,0,19,Buenaventura,36300,0.0,6897.000,43197.000
9,IMP010,Rotterdam Machinery,Netherlands,Compressors,8414,EXW,27500,600,1600,200,5,19,Cartagena,29900,1495.0,5965.050,37360.050
1,IMP002,Hamburg Industrial,Germany,Industrial Valves,8481,CIF,24000,0,0,0,5,19,Cartagena,24000,1200.0,4788.000,29988.000
12,IMP013,Paris Automation,France,Control Panels,8537,EXW,21500,450,1700,190,5,19,Cartagena,23840,1192.0,4756.080,29788.080
0,IMP001,Shanghai Steel Co.,China,Steel Pipes,7306,FOB,18500,0,2100,180,10,19,Cartagena,20780,2078.0,4343.020,27201.020
4,IMP005,Seoul Components,South Korea,Electronic Boards,8534,CIF,19500,0,0,0,10,19,Cartagena,19500,1950.0,4075.500,25525.500
10,IMP011,Shenzhen Electronics,China,Power Supplies,8504,FOB,16800,0,2200,170,10,19,Buenaventura,19170,1917.0,4006.530,25093.530
2,IMP003,Texas Pumps Inc.,USA,Hydraulic Pumps,8413,EXW,15000,500,3000,250,0,19,Buenaventura,18750,0.0,3562.500,22312.500
6,IMP007,Sao Paulo Metals,Brazil,Aluminum Sheets,7606,FOB,14500,0,950,120,10,19,Cartagena,15570,1557.0,3254.130,20381.130
8,IMP009,Toronto Plastics,Canada,Plastic Pellets,3901,FOB,13200,0,1400,160,5,19,Cartagena,14760,738.0,2944.620,18442.620
3,IMP004,Osaka Tech Ltd.,Japan,Sensors,9026,FOB,12000,0,1800,150,5,19,Cartagena,13950,697.5,2783.025,17430.525
5,IMP006,Mumbai Chemicals,India,Industrial Resin,3907,EXW,9800,350,2400,180,5,19,Buenaventura,12730,636.5,2539.635,15906.135
7,IMP008,Milan Textile,Italy,Technical Fabrics,5903,CIF,11000,0,0,0,15,19,Cartagena,11000,1650.0,2403.500,15053.500
11,IMP012,Bangkok Rubber,Thailand,Rubber Components,4016,CIF,9400,0,0,0,5,19,Cartagena,9400,470.0,1875.300,11745.300
14,IMP015,Mexico Industrial,Mexico,Bearings,8482,CIF,8700,0,0,0,5,19,Cartagena,8700,435.0,1735.650,10870.650

In [26]:
df[["Shipment_ID","Incoterm","CIF_Value_USD","Duty_USD","VAT_USD","Total_Import_Cost_USD"]]

,Shipment_ID,Incoterm,CIF_Value_USD,Duty_USD,VAT_USD,Total_Import_Cost_USD
0,IMP001,FOB,20780,2078.0,4343.020,27201.020
1,IMP002,CIF,24000,1200.0,4788.000,29988.000
2,IMP003,EXW,18750,0.0,3562.500,22312.500
3,IMP004,FOB,13950,697.5,2783.025,17430.525
4,IMP005,CIF,19500,1950.0,4075.500,25525.500
5,IMP006,EXW,12730,636.5,2539.635,15906.135
6,IMP007,FOB,15570,1557.0,3254.130,20381.130
7,IMP008,CIF,11000,1650.0,2403.500,15053.500
8,IMP009,FOB,14760,738.0,2944.620,18442.620
9,IMP010,EXW,29900,1495.0,5965.050,37360.050
10,IMP011,FOB,19170,1917.0,4006.530,25093.530
11,IMP012,CIF,9400,470.0,1875.300,11745.300
12,IMP013,EXW,23840,1192.0,4756.080,29788.080
13,IMP014,FOB,36300,0.0,6897.000,43197.000
14,IMP015,CIF,8700,435.0,1735.650,10870.650

Pago total de aranceles

In [29]:
df["Duty_USD"].sum()

np.float64(16016.0)

Pago total de IVA

In [30]:
df["VAT_USD"].sum()

np.float64(55929.54)